version: '3'

services:
  # web:
  #   build:
  #     context: ./web
  #   command: npm run dev
  #   volumes:
  #     - ./web:/app
  #     - node_modules:/app/node_modules
  #   ports:
  #     - "3000:5173"
  #   depends_on:
  #     - backend

  backend:
    build: ./backend
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/app
      - ./backend/data:/app/data
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    environment:
      - DEBUG=True
      - HTTP_PROXY=
      - HTTPS_PROXY=
    depends_on:
      - db
    develop:
      watch:
        - action: sync
          path: ./backend
          target: /app
          ignore:
            - "__pycache__/"
            - "*.pyc"
            - "*.log"

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: myprojectdb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  node_modules:
