# Generated by Django 5.1.1 on 2025-01-19 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_generator', '0004_image_video_alter_image_image_url_alter_video_images_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='video',
            name='topic',
            field=models.CharField(max_length=255),
        ),
    ]
